name: Continous Integration

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Continous Integration
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn
            - name: Lint validation
              run: yarn lint
            - name: Build
              run: yarn build
            - name: Test
              run: yarn jest --verbose --coverage
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
